#!/bin/sh
#
# Modified from http://qiita.com/janus_wel/items/cfc6914d6b7b8bf185b6
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

echo "CPPLINT....."
cpplint=cpplint
sum=0
folders='core/ test/'
        
# for cpp
$cpplint --recursive $folders
sum=$(expr ${sum} + $?)
    
if [ ${sum} -eq 0 ]; then
    exit 0
else
    exit 1
fi
